### PR TITLE
Document decision on casing of fields

### PR DESCRIPTION
**Pull request by dcoxall**
After several discussions we have started to form the internal standards for our core APIs. One of the inital decisions (although minor) was what casing to use.

Seeing as many of our consumers are written using languages that prefer camel case then the decision is that all core APIs will follow that style.

### CODE REVIEW

**Comment by dcoxall** [comment]
Does someone wanna merge this haha. Hello btw

**Comment by oogg** [comment]
Oh. Hello!

**Comment by clarkster** [comment]
Haha  👋  Hi Darren!

**Comment by dcoxall** [comment]
👋  hey!!!! Slowest PR ever

**Pull request merged**
